version: "3"
 
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html/cakephp2/app/webroot/
    ports:
      - 8001:80
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - db
 
  db:
    image: mysql:5
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3309:3306" # 3306ポートにするとローカルのMySQLと被るのでポートをずらす。
    environment:
      MYSQL_DATABASE: cakephp_db
      MYSQL_ROOT_PASSWORD: root_password

volumes:
  db-data:
    external: false